### ISSUE TITLE
Counts not updating properly

### ISSUE THREAD

**Issue by Lusiphur** [WarmedxMints/ODMissionStacker#19]
Been noticing this since the latest version but its getting worse.

Sitting in a res today, in game I have 11 kills on the stack. OD Mission Stacker shows 6 even after a shutdown and read. If you manually increment the kills, it starts keeping track properly again after the next kill.

**Comment by WarmedxMints** [comment]
The reason I added the buttons to increment the values is because the game doesn't always fire a bounty event when you get a kill.  That is more likely when you are killing in a wing.  There is no mission progression event.  There is a mission redirected event which should fire when you complete all the kills the mission wants and it is ready to turn in.  At that point, the app will automatically set the kills to the requirement.

There is nothing which can be done about this.  The app can only guess the kills on a mission as it has to listen for the bounty voucher event and then calculate which mission(s) that kill should be credited to.  If you have reread your journal files and the kills are still the same, chances are the game didn't create a bounty voucher event for them.
