### ISSUE TITLE
Is this still being developed? needs updating as game has changed

### ISSUE THREAD

**Issue by anzial** [WarmedxMints/ODMissionStacker#27]
Nice app, been using for a while but with engineering changes in the game, as missions now are offering a huge variety of mats as rewards just listing the monetary rewards is no longer useful, it'd be nice to show also the other rewards associated with the mission as well. Hopefully the developer still interested in keeping the app current!

**Comment by akuznecov** [comment]
Hello,

I don't think it possible with current application state since information about alternative rewards (such as materials, data, cargo, reputation, influence) is not pushed by game into journals log, so app cannot extract it

There is an example of log entry of `mission accepted` event (added line breaks for better look, but normally it present as single line):
```
{
"timestamp":"2024-10-06T00:55:38Z",
"event":"MissionAccepted",
"Faction":"Ngalinn Jet Natural Incorporated",
"Name":"Mission_MassacreWing",
"LocalisedName":"Kill Brothers of Mainani faction Pirates", 
"TargetType":"$MissionUtil_FactionTag_Pirate;",
"TargetType_Localised":"Pirates",
"TargetFaction":"Brothers of Mainani",
"KillCount":81,
"DestinationSystem":"Mainani",
"DestinationStation":"Mies van der Rohe's Claim",
"Expiry":"2024-10-13T00:24:10Z",
"Wing":true,
"Influence":"++",
"Reputation":"++",
"Reward":39230208,
"MissionID":979550761
}
```
while ingame it looks as:
![image](https://github.com/user-attachments/assets/b751c285-2d05-4ca5-ad33-1ff8860752f2)

**Comment by WarmedxMints** [comment]
@akuznecov is correct.  Unfortunately, the journal logs do not provide anything more than the details of the first reward before it is completed.
